substitutions:
  name: saltlevel
  friendly_name: Saltlevel
  salt_distance: Distance
  salt_procent: Procent
  salt_level_animation: Animation
  salt_height: Height
  salt_version: Version
  salt_fill_last: Refilled on
  salt_fill_salt: Fill salt
  salt_height_min: Min distance salt
  salt_height_max: Max distance salt
  salt_height_fill: Fill salt distance
  salt_ip: IP
  salt_wifi_signal_db: WiFi Signal dB
  salt_wifi_signal_db_percent: WiFi Signal
  salt_uptime: Uptime
  hours: hour
  days: days
  salt_fill_yes: "yes"
  salt_fill_no: "no"
  salt_use_led: Led active
  never: Never
  salt_level_measure: Measurement
  led_brightness: Led brightness

text_sensor:
  # Expose last regeneration information as sensor
  - platform: template
    name: ${salt_fill_last}
    id: salt_fill_last
    icon: mdi:clock-start
    update_interval: never
    lambda: |-
      return id(fill_last);