substitutions:
  name: zoutniveau
  friendly_name: Zoutniveau
  salt_distance: Afstand
  salt_procent: Procent
  salt_level_animation: Animatie
  salt_height: Hoogte
  salt_version: Versie
  salt_fill_last: Bijgevuld op
  salt_fill_salt: Bijvullen
  salt_height_min: Min afstand zout
  salt_height_max: Max afstand zout
  salt_height_fill: Zout bijvullen afstand
  salt_ip: IP
  salt_wifi_signal_db: WiFi Signaal dB
  salt_wifi_signal_db_percent: WiFi Signaal
  salt_uptime: Uptime
  hours: uur
  days: dagen
  salt_fill_yes: ja
  salt_fill_no: nee
  salt_use_led: Led aktief
  never: Nooit
  salt_level_measure: Meting
  led_brightness: Led helderheid

text_sensor:
  # Expose last regeneration information as sensor
  - platform: template
    name: ${salt_fill_last}
    id: salt_fill_last
    icon: mdi:clock-start
    update_interval: never
    lambda: |-
      return id(fill_last);
    filters:   
      - substitute:
        - "Jan -> jan"
        - "Feb -> feb"
        - "Mar -> mar"
        - "Apr -> apr"
        - "May -> mei"
        - "Jun -> jun"
        - "Jul -> jul"
        - "Aug -> aug"
        - "Sep -> sep"
        - "Okt -> okt"
        - "Nov -> nov"
        - "Dec -> dec"
        - "Mon -> maa"
        - "Tue -> din"
        - "Wed -> woe"
        - "Thu -> don"
        - "Fri -> vri"
        - "Sat -> zat"
        - "Sun -> zon" 
