substitutions:
  name: zoutniveau
  friendly_name: Zoutniveau
  salt_distance: Zoutniveau afstand
  salt_procent: Zoutniveau procent
  salt_level_animation: Zoutniveau animatie
  salt_height: Zoutniveau hoogte
  salt_version: Versie
  salt_fill_last: Zout bijgevuld op
  salt_fill_salt: Zout bijvullen
  salt_height_min: Min afstand zout
  salt_height_max: Max afstand zout
  salt_height_fill: Zout bijvullen afstand
  salt_ip: Zoutniveau IP
  salt_wifi_signal_db: WiFi Signaal dB
  salt_wifi_signal_db_percent: WiFi Signaal
  salt_uptime: Uptime
  hours: uur
  days: dagen
  salt_fill_yes: ja
  salt_fill_no: nee

text_sensor:
  # Expose last regeneration information as sensor
  - platform: template
    name: ${salt_fill_last}
    id: salt_fill_last
    icon: mdi:clock-start
    update_interval: never
    lambda: |-
      return id(fill_last);
    filters:   
      - substitute:
        - "Jan -> jan"
        - "Feb -> feb"
        - "Mar -> mar"
        - "Apr -> apr"
        - "Mai -> mei"
        - "Jun -> jun"
        - "Jul -> jul"
        - "Aug -> aug"
        - "Sep -> sep"
        - "Okt -> okt"
        - "Nov -> nov"
        - "Dec -> dec"
        - "Mon -> maa"
        - "Tue -> din"
        - "Wed -> woe"
        - "Thu -> don"
        - "Fri -> vri"
        - "Sat -> zat"
        - "Sun -> zon" 
