views:
  - title: Saltlevel
    path: Saltlevel
    badges: []
    cards:
      - type: vertical-stack
        cards:
          - type: entities
            entities:
              - entity: sensor.saltlevel_procent
                name: Procent
              - entity: sensor.saltlevel_height
                name: Height
              - entity: sensor.saltlevel_distance
                name: Distance
              - entity: sensor.saltlevel_fill_salt
                name: Fill
              - entity: sensor.saltlevel_refilled_on
                name: Filled on
            title: Saltlevel
          - type: entities
            entities:
              - entity: light.saltlevel_led
                name: Led
              - entity: switch.saltlevel_measurement
                name: Measurement
              - entity: number.saltlevel_led_brightness
                name: Led brightness
              - entity: number.saltlevel_max_distance_salt
                name: Max distance salt
              - entity: number.saltlevel_min_distance_salt
                name: Min distance salt
              - entity: number.saltlevel_fill_salt_distance
                name: Fill salt distance
            show_header_toggle: false
      - elements:
          - entity: sensor.saltlevel_animation
            image: local/images/softener.png
            state_image:
              '0': local/images/softener0.png
              '10': local/images/softener10.png
              '20': local/images/softener20.png
              '40': local/images/softener40.png
              '60': local/images/softener60.png
              '80': local/images/softener80.png
              '100': local/images/softener100.png
            style:
              left: 0%
              top: 0%
              transform: scale(1,1)
            tap_action:
              action: none
            type: image
        image: local/images/softener.png
        panel: true
        type: picture-elements
      - type: entities
        entities:
          - entity: sensor.saltlevel_uptime
            name: Uptime
          - entity: sensor.saltlevel_version
            name: Version
          - entity: sensor.saltlevel_wifi_signal
            name: WiFi Signal
          - entity: sensor.saltlevel_ip
            name: Saltlevel IP