substitutions:
  name: saltlevel
  friendly_name: Saltlevel
  salt_distance: Saltlevel distance
  salt_procent: Saltlevel procent
  salt_level_animation: Saltlevel animation
  salt_height: Saltlevel height
  salt_version: Version
  salt_fill_last: Salt refilled on
  salt_fill_salt: Fill salt
  salt_height_min: Min distance salt
  salt_height_max: Max distance salt
  salt_height_fill: Fill salt distance
  salt_ip: Saltlevel IP
  salt_wifi_signal_db: WiFi Signal dB
  salt_wifi_signal_db_percent: WiFi Signal
  salt_uptime: Uptime
  hours: hour
  days: days
  salt_level_yes: "yes"
  salt_level_no: "no"